openapi: 3.0.0
info:
  title: Test d'orientation du COVID19
  version: '2020-03-30 20:01:39.836837Z'
servers:
  - url: 'http://localhost:4000'
    variables: {}
paths:
  /questionnaire:
    post:
      parameters: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QuestionnaireResponse'
          description: Questionnaire
      tags: []
      callbacks: {}
      deprecated: false
      description: Évaluer le test d'orientation du COVID19
      operationId: QuestionnaireController.create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionnaireRequest'
        description: Paramètres du test d'orientation
        required: true
      summary: Évaluer le test d'orientation du COVID19
components:
  responses: {}
  schemas:
    Calculations:
      description: >-
        [Calculations](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/implementation.org#conseils-pour-limpl%C3%A9mentation-de-lalgorithme)
      example:
        bmi_more_30: true
        fever: true
        gravity_factors: 3
        gravity_factors_major: 1
        gravity_factors_minor: 2
        risk_factors: 1
      properties:
        bmi_more_30:
          description: Si la personne a au moins 30 d'IMC en kg/(cm/100)2
          type: boolean
        fever:
          description: Indicateur de fièvre
          type: boolean
        gravity_factors:
          description: Facteurs de gravité mineurs + majeurs
          type: integer
        gravity_factors_major:
          description: Facteurs de gravité majeurs
          type: integer
        gravity_factors_minor:
          description: Facteurs de gravité mineurs
          type: integer
        risk_factors:
          description: Facteurs pronostique défavorables liés au terrain
          type: integer
      required:
        - bmi_more_30
        - fever
        - gravity_factors
        - gravity_factors_minor
        - gravity_factors_major
        - risk_factors
      title: Calculations
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Calculations
    Metadata:
      description: >-
        [Caractéristiques du
        questionnaire](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        algo_version: '2020-03-29 15:20:11.875767Z'
        date: '2020-03-29 15:20:11.875767Z'
        duration: 3600
        form_version: '2020-03-29 15:20:11.875767Z'
      properties:
        algo_version:
          description: Version de l'algorithme médical
          format: date-time
          type: string
        date:
          description: Date de fin de remplissage du questionnaire
          format: date-time
          type: string
        duration:
          description: Durée de remplissage du questionnaire (seconds)
          type: integer
        form_version:
          description: Version du questionnaire
          format: date-time
          type: string
      required:
        - duration
      title: Metadata
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Metadata
    Orientation:
      description: >-
        [Orientation du questionnaire
        COVID19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
      example:
        code: orientation_SAMU
      properties:
        code:
          description: >-
            [Orientations
            possibles](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#conclusions-possibles)
          enum:
            - FIN1
            - FIN2
            - FIN3
            - FIN4
            - orientation_SAMU
            - FIN6
            - FIN7
            - FIN8
          type: string
      required:
        - code
      title: Orientation
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Orientation
    Patient:
      description: >-
        [Caractéristiques du
        patient](https://docs.google.com/spreadsheets/d/1Ne7QEp_oMHRxxYhqT56AWugfTaywu-cNRZsWPrMGvkY/edit#gid=0)
      example:
        age_less_15: false
        age_less_50: false
        age_less_70: false
        age_more_70: true
        height: 173
        postal_code: '75000'
        weight: 65.5
      properties:
        age_less_15:
          description: Si la personne a moins de 15 ans
          type: boolean
        age_less_50:
          description: Si la personne a moins de 50 ans
          type: boolean
        age_less_70:
          description: Si la personne a moins de 70 ans
          type: boolean
        age_more_70:
          description: Si la personne a au moins 70 ans
          type: boolean
        height:
          description: Quelle est votre taille en centimètres ?
          type: integer
        postal_code:
          description: Code postal
          type: string
        weight:
          description: Quel est votre poids en kilogrammes ?
          type: number
      title: Patient
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Patient
    Questionnaire:
      description: >-
        [Algorithme d'orientation du
        COVID19](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#pr%C3%A9sentation-de-lalgorithme-dquestionnaire-covid19)
      example:
        calculations:
          bmi_more_30: true
          fever: true
          gravity_factors: 3
          gravity_factors_major: 1
          gravity_factors_minor: 2
          risk_factors: 1
        metadata:
          algo_version: '2020-03-29 15:20:11.875767Z'
          date: '2020-03-29 15:20:11.875767Z'
          duration: 3600
          form_version: '2020-03-29 15:20:11.875767Z'
        orientation:
          code: orientation_SAMU
        patient:
          age_less_15: false
          age_less_50: false
          age_less_70: false
          age_more_70: true
          height: 173
          postal_code: '75000'
          weight: 65.5
        risk_factors:
          breathing_disease: true
          cancer: true
          diabetes: true
          heart_disease: true
          immunosuppressant_disease: true
          immunosuppressant_drug: true
          kidney_disease: true
          liver_disease: true
          pregnant: '1'
        symptoms:
          agueusia_anosmia: true
          breathlessness: true
          cough: true
          diarrhea: true
          feeding_day: true
          fever: false
          sore_throat_aches: true
          temperature_cat: '[35.5, 35.7]'
          tiredness: true
          tiredness_details: true
      properties:
        calculations:
          $ref: '#/components/schemas/Calculations'
        metadata:
          $ref: '#/components/schemas/Metadata'
        orientation:
          $ref: '#/components/schemas/Orientation'
        patient:
          $ref: '#/components/schemas/Patient'
        risk_factors:
          $ref: '#/components/schemas/RiskFactors'
        symptoms:
          $ref: '#/components/schemas/Symptoms'
      required:
        - metadata
        - patient
        - symptoms
        - risk_factors
      title: Questionnaire
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Questionnaire
    QuestionnaireRequest:
      description: Corps de la requête POST pour lancer l'algorithme d'orientation
      example:
        questionnaire:
          metadata:
            duration: 3600
          patient:
            age_less_15: false
            age_less_50: false
            age_less_70: false
            age_more_70: true
            height: 173
            postal_code: '75000'
            weight: 65.5
          risk_factors:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: true
            immunosuppressant_disease: true
            immunosuppressant_drug: true
            kidney_disease: true
            liver_disease: true
            pregnant: '1'
          symptoms:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding_day: true
            fever: false
            sore_throat_aches: true
            temperature_cat: '[35.5, 35.7]'
            tiredness: true
            tiredness_details: true
      properties:
        questionnaire:
          anyOf:
            - $ref: '#/components/schemas/Questionnaire'
      required:
        - questionnaire
      title: QuestionnaireRequest
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireRequest
    QuestionnaireResponse:
      description: Réponse de l'algorithme d'orientation
      example:
        data:
          calculations:
            bmi_more_30: true
            fever: true
            gravity_factors: 3
            gravity_factors_major: 1
            gravity_factors_minor: 2
            risk_factors: 1
          metadata:
            algo_version: '2020-03-30 20:01:39.836837Z'
            date: '2020-03-29 15:20:11.875767Z'
            duration: 3600
            form_version: '2020-03-30 20:01:39.836837Z'
          orientation:
            code: FIN5
          patient:
            age_less_15: false
            age_less_50: false
            age_less_70: false
            age_more_70: true
            height: 173
            postal_code: '75000'
            weight: 65.5
          risk_factors:
            breathing_disease: true
            cancer: true
            diabetes: true
            heart_disease: true
            immunosuppressant_disease: true
            immunosuppressant_drug: true
            kidney_disease: true
            liver_disease: true
            pregnant: '1'
          symptoms:
            agueusia_anosmia: true
            breathlessness: true
            cough: true
            diarrhea: true
            feeding_day: true
            fever: false
            sore_throat_aches: true
            temperature_cat: '[35.5, 35.7]'
            tiredness: true
            tiredness_details: true
      properties:
        data:
          $ref: '#/components/schemas/Questionnaire'
      title: QuestionnaireResponse
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.QuestionnaireResponse
    RiskFactors:
      description: >-
        [Questions sur les facteurs pronostiques défavorables au
        terrain](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-facteurs-pronostiques-d%C3%A9favorables-au-terrain)
      example:
        breathing_disease: true
        cancer: true
        diabetes: true
        heart_disease: true
        immunosuppressant_disease: true
        immunosuppressant_drug: true
        kidney_disease: true
        liver_disease: true
        pregnant: '1'
      properties:
        breathing_disease:
          description: >-
            Avez-vous une maladie respiratoire ? Ou êtes-vous suivi par un
            pneumologue ?
          type: boolean
        cancer:
          description: Avez-vous ou avez-vous eu un cancer ?
          type: boolean
        diabetes:
          description: Êtes-vous diabétique ?
          type: boolean
        heart_disease:
          description: >-
            Avez-vous une tension artérielle mal équilibrée ? Ou une maladie
            cardiaque ou vasculaire ? Ou prenez-vous un traitement à visée
            cardiologique ?
          type: boolean
        immunosuppressant_disease:
          description: >-
            Avez-vous une maladie connue pour diminuer vos défenses immunitaires
            ?
          type: boolean
        immunosuppressant_drug:
          description: Prenez-vous un traitement immunosuppresseur ?
          type: boolean
        kidney_disease:
          description: Avez-vous une insuffisance rénale chronique dialysée ?
          type: boolean
        liver_disease:
          description: Avez-vous une maladie chronique du foie ?
          type: boolean
        pregnant:
          description: Êtes-vous enceinte ?
          enum:
            - '1'
            - '0'
            - DNK
          type: string
      title: RiskFactors
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.RiskFactors
    Symptoms:
      description: >-
        [Questions sur les
        symptômes](https://github.com/Delegation-numerique-en-sante/covid19-algorithme-questionnaire/blob/master/pseudo-code.org#questions-sur-les-sympt%C3%B4mes)
      example:
        agueusia_anosmia: true
        breathlessness: true
        cough: true
        diarrhea: true
        feeding_day: true
        fever: false
        sore_throat_aches: true
        temperature_cat: '[35.5, 35.7]'
        tiredness: true
        tiredness_details: true
      properties:
        agueusia_anosmia:
          description: >-
            Avez-vous noté une forte diminution de votre goût ou de l’odorat ces
            derniers jours ?
          type: boolean
        breathlessness:
          description: >-
            Dans les dernières 24 heures, avez-vous noté un manque de souffle
            INHABITUEL lorsque vous parlez ou faites un petit effort ?
          type: boolean
        cough:
          description: >-
            Avez-vous une toux ou une augmentation de votre toux habituelle ces
            derniers jours ?
          type: boolean
        diarrhea:
          description: >-
            Avez-vous de la diarrhée ces dernières 24 heures (au moins 3 selles
            molles) ?
          type: boolean
        feeding_day:
          description: >-
            Êtes-vous dans l’impossibilité de vous alimenter ou boire DEPUIS 24
            HEURES OU PLUS ?
          type: boolean
        fever:
          description: >-
            Pensez-vous avoir eu de la fièvre ces derniers jours (frissons,
            sueurs) ?
          type: boolean
        sore_throat_aches:
          description: Avez-vous un mal de gorge apparu ces derniers jours ?
          type: boolean
        temperature_cat:
          description: Quelle est votre température ?
          enum:
            - '(−∞, 35.4]'
            - '[35.5, 35.7]'
            - '[37.8, 38.9]'
            - '[39, +∞)'
            - DNK
          type: string
        tiredness:
          description: Avez-vous une fatigue inhabituelle ces derniers jours ?
          type: boolean
        tiredness_details:
          description: >-
            Cette fatigue vous oblige-t-elle à vous reposer plus de la moitié de
            la journée ?
          type: boolean
      title: Symptoms
      type: object
      x-struct: Elixir.Covid19QuestionnaireWeb.Schemas.Symptoms
security: []
tags: []

